# Generated by Django 4.2.7 on 2023-11-29 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
