# Generated by Django 4.2.7 on 2023-12-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruddecApp', '0002_alter_deposits_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='status',
            field=models.CharField(choices=[('Successful', '1'), ('Failed', '3'), ('Pending', '2')], default='1', max_length=20),
        ),
    ]
