# Generated by Django 4.2.7 on 2023-12-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruddecApp', '0004_dailywinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywinner',
            name='amount',
        ),
        migrations.AddField(
            model_name='dailywinner',
            name='winning_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='WinnerDetails',
            fields=[
                ('winning_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('welfare_fund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fruddecApp.dailywinner')),
            ],
        ),
    ]
