# Generated by Django 4.2.7 on 2023-12-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruddecApp', '0005_remove_dailywinner_amount_dailywinner_winning_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeDistributionDetails',
            fields=[
                ('prize_distribution_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('welfare_fund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='dailywinner',
            name='monthly_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='WinnerDetails',
        ),
        migrations.AddField(
            model_name='prizedistributiondetails',
            name='winner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fruddecApp.dailywinner'),
        ),
    ]
