# Generated by Django 4.2.9 on 2024-01-14 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruddecApp', '0006_prizedistributiondetails_dailywinner_monthly_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrudulentActivityDetail',
            fields=[
                ('frudulent_activity_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_occurance', models.DateTimeField()),
                ('log', models.CharField(default='', max_length=500)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frudulentactivity', to='fruddecApp.deposits')),
            ],
        ),
    ]
