# Generated by Django 4.2.9 on 2024-02-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruddecApp', '0007_frudulentactivitydetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frudulentactivitydetail',
            name='date_of_occurance',
        ),
    ]
